name: Train Model CI

on:
  push:
    branches:
      - main

jobs:
  train:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0

      - name: Verify Files
        run: |
          ls
          ls MLProject

      - name: Run MLflow Project
        env:
          MLFLOW_ALLOW_FILE_STORE: "true"
        run: |
          mlflow run ./MLProject --env-manager local

      - name: Upload Model Artifact
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: MLProject/model.pkl